/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "I2C.h"
#include "I2C_I2C.h"
#include "I2C_PINS.h"
#include "I2C_I2C_PVT.h"
#include "I2C_PVT.h"
#include "I2C_BOOT.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "SPI.h"
#include "SPI_SPI_UART.h"
#include "SPI_PINS.h"
#include "SPI_SPI_UART_PVT.h"
#include "SPI_PVT.h"
#include "SPI_BOOT.h"
#include "ant1.h"
#include "ant1_aliases.h"
#include "ant2.h"
#include "ant2_aliases.h"
#include "ant3.h"
#include "ant3_aliases.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "SPI_SCBCLK.h"
#include "SPI_ss2_m.h"
#include "SPI_ss2_m_aliases.h"
#include "SPI_ss1_m.h"
#include "SPI_ss1_m_aliases.h"
#include "SPI_sclk_m.h"
#include "SPI_sclk_m_aliases.h"
#include "SPI_mosi_m.h"
#include "SPI_mosi_m_aliases.h"
#include "SPI_ss0_m.h"
#include "SPI_ss0_m_aliases.h"
#include "SPI_SCB_IRQ.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cm0plus_psoc4.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

